package com.sp.app.kafka.vo;

import java.io.Serializable;
import java.util.Date;

//Jackson annotation used to specify how to format fields and properties for JSON output.
//import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * Class used for serialize represented data
 * 
 * @author Rengo
 *
 */

public class SPData implements Serializable {

	/**
	 * Added autogenerated versionUID Should be changed whenever make a change that
	 * is incompatible under the rules given in the Versioning of Serializable
	 * Objects
	 */
	private static final long serialVersionUID = 9202107342425504862L;
	private String id;
	private float avg;
	private String country;
	private String region;
	private Date date;

	/**
	 * @return the id
	 */
	public String getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * @return the avg
	 */
	public float getAvg() {
		return avg;
	}

	/**
	 * @param avg the avg to set
	 */
	public void setAvg(float avg) {
		this.avg = avg;
	}

	/**
	 * @return the country
	 */
	public String getCountry() {
		return country;
	}

	/**
	 * @param country the country to set
	 */
	public void setCountry(String country) {
		this.country = country;
	}

	/**
	 * @return the region
	 */
	public String getRegion() {
		return region;
	}

	/**
	 * @param region the region to set
	 */
	public void setRegion(String region) {
		this.region = region;
	}

	/**
	 * @return the date
	 */
	public Date getDate() {
		return date;
	}

	/**
	 * @param date the date to set
	 */
	public void setDate(Date date) {
		this.date = date;
	}

	/**
	 * @param id
	 * @param avg
	 * @param country
	 * @param region
	 * @param date
	 */
	public SPData(String id, float avg, String country, String region, Date date) {
		super();
		this.id = id;
		this.avg = avg;
		this.country = country;
		this.region = region;
		this.date = date;
	}

	public SPData() {

	}

}
